### ISSUE TITLE
Make sure you set alamofire acceptable content types

### ISSUE THREAD

**Issue by leojkwan** [smilefam/SendBird-iOS#21]
I was trying out the swift repo and after uploading some dummy images, the thumbnail would not change it's placeholder purple image view. After debugging the error messages, I realized that in 

```
imageDownloader.download(
            urlRequest,
            receiptID: downloadID,
            filter: filter,
            progress: progress,
            progressQueue: progressQueue,
            completion: { [weak self] response in
```

the response says make sure you allow acceptable types image/jpg, image/png etc.

Calling this class method on alamofire before the image fetch fixes it.
```
DataRequest.addAcceptableImageContentTypes(["image/jpg"])
```

**Comment by famous90** [comment]
@leojkwan Sorry to reply late. Is it right it happens when you update thumbnail image by Alamofire? I think this problem is occurred in Alamofire and [this issue](https://github.com/Alamofire/AlamofireImage/issues/301) is same problem. If you update Alamofire(and if Alamofire resolved this issue), it'll be solved. Thank you for your suggestion.

**Comment by leojkwan** [comment]
thanks @ahnjungho !
